syntax = "proto3";

package morphing.protos;

import "protos/geometry.proto";

message EdgeContractionProto {
  uint64 edge_id = 1;
  uint64 kept_vertex_id = 2;
  uint64 removed_vertex_id = 3;
}

message EdgeExpansionProto {
  uint64 edge_id = 1;
  uint64 new_vertex_1_id = 2;
  uint64 new_vertex_2_id = 3;
}

message VertexMoveProto {
  uint64 vertex_id = 1;
  oneof destination {
    Vector3dProto double_dest = 2;
    ExtendedPrecisionVectorProto extended_dest = 3;
  }
}

message MorphOperationProto {
  oneof operation {
    EdgeContractionProto contraction = 1;
    EdgeExpansionProto expansion = 2;
    VertexMoveProto move = 3;
  }
}

message PseudomorphSequenceProto {
  repeated MorphOperationProto operations = 1;
}

message MorphKeyframeProto {
  double time = 1; // Normalized time t in [0, 1]
  repeated VertexProto vertices = 2;
}

message CompiledMorphProto {
  repeated MorphKeyframeProto keyframes = 1;
}
