syntax = "proto3";

package morphing.protos;

import "protos/geometry.proto";

// A vertex move corresponds to moving a vertex in an embedding to some new destination within its star's kernel.
// This location can include a point on the surface not coincident to a vertex of the embedding, but it could also correspond to a vertex of the embedding.
// When moving a vertex u to a vertex v, it is implied the edge {u, v} exists in the underlying graph and that after the contraction,
// vertices u and v join to form a single vertex where v becomes the representative.
// When moving a vertex u to a point p in its star's kernel, it is possible this vertex starts off coincident to an existing
// vertex v. If so, this operation is called an edge expansion and the vertex u splits off from v as we move u to p.
message VertexMove {
  // The type of operation.
  enum Operation {
    EDGE_CONTRACTION = 0;
    EDGE_EXPANSION   = 1;
    VERTEX_MOVE      = 2;
  }

  Operation op               = 1;
  uint64    vertex_moving_id = 2;
  oneof destination {
    // implies edge contraction: we move vertex_moving_id to vertex_destination_id.
    // after completion, vertex_moving_id will no longer be in the graph.
    uint64 vertex_destination_id = 3;
    // implies either edge expansion or moving vertex to point in its star's kernel.
    // in either case, the vertex will be within the graph. in the former case, it goes
    // from not being in the graph to being in the graph.
    Point destination_point = 4;
  }
}

message RotationMatrix {
  repeated double elements = 1; // in row-major order
}

message PseudomorphStep {
  oneof operation {
    VertexMove     vertex_move = 1;
    RotationMatrix rotation    = 2;
  }
}

// A sequence of operations that transform the start graph into the end graph.
// This sequence is called a pseudomorph since it allows for vertices to move
// and lie on top of other vertices.
message Pseudomorph {
  IsomorphicGraphEmbeddings embedding_pair = 1;
  repeated PseudomorphStep  steps          = 2;
}
